name: Publish Canary

on:
  push:
    branches: [canary]
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Ensure npm supports trusted publishing
        run: npm install -g npm@latest

      - name: Install deps
        run: npm ci

      - name: Publish to npm @canary
        env:
          NPM_CONFIG_PROVENANCE: 'true'
        run: npx changeset publish --no-git-tag